// DOM element bindings — imported by any module that touches the DOM.
const $ = (id) => {
  const el = document.getElementById(id);
  if (!el) throw new Error(`Missing #${id}`);
  return el;
};

export const els = {
  form: $("searchForm"),
  q: $("q"),
  suggest: $("suggest"),
  searchBtn: $("searchBtn"),
  locateBtn: $("locateBtn"),
  status: $("status"),
  place: $("place"),
  meta: $("meta"),
  badge: $("badge"),
  wxIcon: $("wxIcon"),
  tempValue: $("tempValue"),
  tempUnit: $("tempUnit"),
  wxText: $("wxText"),
  wxSub: $("wxSub"),
  stats: $("stats"),
  feels: $("feels"),
  hum: $("hum"),
  wind: $("wind"),
  windDir: $("windDir"),
  precip: $("precip"),
  popNow: $("popNow"),
  dew: $("dew"),
  uv: $("uv"),
  uvMax: $("uvMax"),
  vis: $("vis"),
  press: $("press"),
  sun: $("sun"),
  sky: $("sky"),
  sunIcon: $("sunIcon"),
  sunriseTime: $("sunriseTime"),
  sunsetTime: $("sunsetTime"),
  sunNow: $("sunNow"),
  sunDot: $("sunDot"),
  moonIcon: $("moonIcon"),
  moonriseTime: $("moonriseTime"),
  moonsetTime: $("moonsetTime"),
  moonNow: $("moonNow"),
  moonDot: $("moonDot"),
  skyNote: $("skyNote"),
  hourlyHint: $("hourlyHint"),
  hourly: $("hourly"),
  daily: $("daily"),
  aqi: $("aqi"),
  aqiCat: $("aqiCat"),
  pm25: $("pm25"),
  pm10: $("pm10"),
  o3: $("o3"),
  no2: $("no2"),
  airStatus: $("airStatus"),
  unitBtn: $("unitBtn"),
  pinBtn: $("pinBtn"),
  favs: $("favs"),
  tempArc:     $("tempArc"),
  weatherFx:   $("weatherFx"),
  clearBtn:    $("clearBtn"),
  offlineBanner: $("offlineBanner"),
  shareBtn:    $("shareBtn"),
  aqiGauge:    $("aqiGauge"),
  aqiGaugeDot: $("aqiGaugeDot"),
  themeToggleBtn: $("themeToggleBtn"),
  recents:     $("recents"),
  hourlyOuter: $("hourlyOuter"),
  hourlyScrollHint: $("hourlyScrollHint"),
};
